version: "3.8"

services: 
  teacher-server:
    container_name: teacher-server
    build:
      context: .
      dockerfile: dockerfiles/teacher-nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./teacher-app:/var/www/html
      - ./nginx/teacher-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - teacher-php
      - mysql

  student-server:
    container_name: student-server
    build:
      context: .
      dockerfile: dockerfiles/student-nginx.dockerfile
    ports: 
      - '5000:80'
    volumes: 
      - ./student-app:/var/www/html
      - ./nginx/student-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - student-php
      - mysql

  teacher-php:
    container_name: teacher-app-php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./teacher-app:/var/www/html:delegated

  student-php:
    container_name: student-app-php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./student-app:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=school
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret